ccflags-y += -I$(srctree)/drivers/misc/mediatek/base/power/cpufreq_v1/src
ccflags-y += -I$(srctree)/drivers/misc/mediatek/base/power/cpufreq_v1/src/mach/mt6768
ccflags-y += -I$(srctree)/drivers/misc/mediatek/sspm/v1/
ccflags-y += -I$(srctree)/drivers/misc/mediatek/include
ccflags-y += -Wno-error=implicit-function-declaration
ccflags-y += -I$(srctree)/drivers/misc/mediatek/sspm/v1
ccflags-y += -I$(srctree)/drivers/misc/mediatek/base/power/cpufreq_v1/src/mach/mt6768
